/**
 * @param { import('knex').Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('product').del()
  await knex('product').insert([
    {
      product_name: 'Logitech MK270 Wireless Keyboard And Mouse Combo',
      price: 27.99,
      stock: 100,
      description: 'Logitech MK270 Wireless Keyboard And Mouse Combo For Windows, 2.4 GHz Wireless, Compact Mouse, 8 Multimedia And Shortcut Keys, For PC, Laptop - Black',
      category_id: 6,
      manufacturer_id: 1,
      discount: 0,
      type: 'keyboard',
      tag: 'featured',
    },
    {
      product_name: 'NPET K10V3PRO Gaming Keyboard',
      description: 'NPET K10V3PRO Gaming Keyboard, RGB Backlit Keys, Spill-Resistant, Customizable Keys, Dedicated Multi-Media Keys – Black',
      price: 12.49,
      stock:90,
      category_id: 6,
      manufacturer_id: 2,
      discount: 0,
      type: 'keyboard',
      tag: 'featured',
    },
    {
      product_name: 'SteelSeries Arctis Nova 1 Multi-System Gaming Headset',
      description: 'SteelSeries Arctis Nova 1 Multi-System Gaming Headset — Hi-Fi Drivers — 360° Spatial Audio — Comfort Design — Durable — Ultra Lightweight — Noise-Cancelling Mic — PC, PS5/PS4, Switch, Xbox - Black',
      price: 59.99,
      stock: 80,
      category_id: 1,
      manufacturer_id: 3,
      discount: 0,
      type: 'headset',
      tag: 'new',
    },
    {
      product_name: 'Logitech K120 Wired Keyboard for Windows',
      description: 'Logitech K120 Wired Keyboard for Windows, Plug and Play, Full-Size, Spill-Resistant, Curved Space Bar, Compatible with PC, Laptop - Black',
      price: 12.34,
      stock: 80,
      category_id: 2,
      manufacturer_id: 1,
      discount: 0.10,
      type: 'keyboard',
      tag: 'sale',
    },
    {
      product_name: 'SteelSeries Apex 3 RGB Gaming Keyboard',
      description: 'SteelSeries Apex 3 RGB Gaming Keyboard – 10-Zone RGB Illumination – IP32 Water Resistant – Premium Magnetic Wrist Rest (Whisper Quiet Gaming Switch)',
      price: 35.99,
      stock: 70,
      category_id: 4,
      manufacturer_id: 3,
      discount: 0,
      type: 'keyboard',
      tag: 'sale',
    },
    {
      product_name: 'Rii RK907 Ultra-Slim Compact USB Wired Keyboard for Mac and PC',
      description: 'Rii RK907 Ultra-Slim Compact USB Wired Keyboard for Mac and PC,Windows 10/8 / 7 / Vista/XP (Black) (1PCS)',
      price: 14.99,
      stock: 85,
      category_id: 2,
      manufacturer_id: 3,
      discount: 0,
      type: 'keyboard',
      tag: 'sale',
    },
    {
      product_name: 'Logitech K270 Wireless Keyboard for Windows',
      description: 'Logitech K270 Wireless Keyboard for Windows, 2.4 GHz Wireless, Full-Size, Number Pad, 8 Multimedia Keys, 2-Year Battery Life, Compatible with PC, Laptop, Black',
      price: 24.95,
      stock: 67,
      category_id: 1,
      manufacturer_id: 5,
      discount: 0,
      type: 'keyboard',
      tag: 'featured',
    },
    {
      product_name: 'Dell Wired Keyboard',
      description: 'Dell Wired Keyboard - Black KB216 (580-ADMT)',
      price: 15.99,
      stock: 70,
      category_id: 1,
      manufacturer_id: 6,
      discount: 0,
      type: 'keyboard',
      tag: 'new',
    },
    {
      product_name: 'AULA F99 Wireless Mechanical Keyboard',
      description: 'AULA F99 Wireless Mechanical Keyboard,Tri-Mode BT5.0/2.4GHz/USB-C Hot Swappable Custom Keyboard,Pre-lubed Linear Switches,Gasket Structure,RGB Backlit Gaming Keyboard for PC/Tablet/PS/Xbox',
      price: 69.95,
      stock: 30,
      category_id: 4,
      manufacturer_id: 1,
      discount: 0,
      type: 'keyboard',
      tag: 'featured',
    },
    {
      product_name: 'Rii RK100+ Multiple Color Rainbow LED Backlit Keyboard',
      description: 'Rii RK100+ Multiple Color Rainbow LED Backlit Large Size USB Wired Mechanical Feeling Multimedia PC Gaming Keyboard,Office Keyboard for Working or Primer Gaming,Office Device',
      price: 16.99,
      stock: 45,
      category_id: 8,
      manufacturer_id: 5,
      discount: 0,
      type: 'keyboard',
      tag: 'sale',
    },
    {
      product_name: 'Amazon Basics Wired Keyboard',
      description: 'Amazon Basics Wired Keyboard, Full-Sized, QWERTY Layout, Black',
      price: 14.08,
      stock: 70,
      category_id: 3,
      manufacturer_id: 2,
      discount: 0,
      type: 'keyboard',
      tag: 'new',
    },
    {
      product_name: 'Arteck 2.4G Wireless Keyboard',
      description: 'Arteck 2.4G Wireless Keyboard Stainless Steel Ultra Slim Full Size Keyboard with Numeric Keypad for Computer/Desktop/PC/Laptop/Surface/Smart TV and Windows 10/8/ 7 Built in Rechargeable Battery',
      price: 49.99,
      stock: 65,
      category_id: 1,
      manufacturer_id: 2,
      discount: 0,
      type: 'keyboard',
      tag: 'featured',
    },
    {
      product_name: 'Logitech G915 LIGHTSPEED RGB Mechanical Gaming Keyboard',
      description: 'Logitech G915 LIGHTSPEED RGB Mechanical Gaming Keyboard, Low Profile GL Clicky Key Switch, LIGHTSYNC RGB, Advanced LIGHTSPEED Wireless and Bluetooth Support - Clicky,Black',
      price: 149.99,
      stock: 25,
      category_id: 1,
      manufacturer_id: 2,
      discount: 0.3,
      type: 'keyboard',
      tag: 'new',
    },
    {
      product_name: 'Membrane Gaming Wired Keyboard for PC Laptop Windows Gamer',
      description: '65% Gaming Keyboard, Wired Backlit Mini Keyboard, Ultra-Compact Anti-Ghosting No-Conflict 68 Keys Membrane Gaming Wired Keyboard for PC Laptop Windows Gamer',
      price: 19.99,
      stock: 15,
      category_id: 8,
      manufacturer_id: 3,
      discount: 0.12,
      type: 'keyboard',
      tag: 'new',
    },
    {
      product_name: 'Logitech Wave Keys Wireless Ergonomic Keyboard',
      description: 'Logitech Wave Keys Wireless Ergonomic Keyboard with Cushioned Palm Rest, Comfortable Natural Typing, Easy-Switch, Bluetooth, Logi Bolt Receiver, for Multi-OS, Windows/Mac - Graphite',
      price: 69.99,
      stock: 15,
      category_id: 8,
      manufacturer_id: 6,
      discount: 0.3,
      type: 'keyboard',
      tag: 'sale',
    },
    {
      product_name: 'MageGee Portable Mechanical Gaming Keyboard',
      description: 'MageGee Portable 60% Mechanical Gaming Keyboard, MK-Box LED Backlit Compact 68 Keys Mini Wired Office Keyboard with Red Switch for Windows Laptop PC Mac - Black/Grey',
      price: 30.99,
      stock: 95,
      category_id: 5,
      manufacturer_id: 4,
      discount: 0.5,
      type: 'keyboard',
      tag: 'new',
    },
    {
      product_name: 'MOFII Wireless Keyboard',
      description: 'MOFII Wireless Keyboard and Mouse Combo,2.4GHz Retro Full-Size Keyboard with Number Pad and Cute Mouse for Computer PC Desktops Laptop WindowsxP/7/8/10(Milk Tea Colorful-B)',
      price: 39.99,
      stock: 34,
      category_id: 4,
      manufacturer_id: 3,
      discount: 0.6,
      type: 'keyboard',
      tag: 'featured',
    },
    {
      product_name: 'WallarGe Wireless Headphones',
      description: 'WallarGe Wireless Headphones for TV Watching, TV Headphones Wireless for Seniors, Easy Setup and Comfortable Bluetooth Headphones, 25 Hours Play and No Audio Delay',
      price: 40.99,
      stock: 45,
      category_id: 1,
      manufacturer_id: 5,
      discount: 0,
      type: 'headset',
      tag: 'new',
    },
    {
      product_name: 'Bose QuietComfort 35 II Wireless Headphones',
      description: 'Bose QuietComfort 35 II Wireless Bluetooth Headphones, Noise-Cancelling, with Alexa Voice Control - Black',
      price: 29.00,
      stock: 15,
      category_id: 1,
      manufacturer_id: 6,
      discount: 0.2,
      type: 'headset',
      tag: 'sale',
    },
    {
      product_name: 'SteelSeries Arctis 7P Wireless Gaming Headset',
      description: 'SteelSeries Arctis 7P Wireless Gaming Headset – Lossless 2.4 GHz Wireless – Detachable ClearCast Microphone – for PlayStation 5 and PlayStation 4 - Black',
      price: 149.99,
      stock: 20,
      category_id: 3,
      manufacturer_id: 3,
      discount: 0,
      type: 'headset',
      tag: 'new',
    },
    {
      product_name: 'Logitech G PRO X Wireless LIGHTSPEED Gaming Headset',
      description: 'Logitech G PRO X Wireless LIGHTSPEED Gaming Headset with Blue VO!CE Mic Filter Tech, 50 mm PRO-G Drivers, and DTS Headphone:X 2.0 Surround Sound',
      price: 199.99,
      stock: 10,
      category_id: 3,
      manufacturer_id: 2,
      discount: 0.3,
      type: 'headset',
      tag: 'sale',
    },
    {
      product_name: 'Razer Kraken X Ultralight Gaming Headset',
      description: 'Razer Kraken X Ultralight Gaming Headset: 7.1 Surround Sound - Lightweight Aluminum Frame - Bendable Cardioid Microphone - for PC, PS4, PS5, Switch, Xbox One, Xbox Series X & S, Mobile - Black',
      price: 39.99,
      stock: 30,
      category_id: 2,
      manufacturer_id: 4,
      discount: 0,
      type: 'headset',
      tag: 'new',
    },
    {
      product_name: 'HyperX Cloud Stinger Core - Wireless Gaming Headset',
      description: 'HyperX Cloud Stinger Core - Wireless Gaming Headset, for PS4, PS5, PC, Lightweight, Durable Steel Sliders, Noise-Cancelling Microphone, up to 17 Hour Battery Life',
      price: 79.99,
      stock: 25,
      category_id: 2,
      manufacturer_id: 1,
      discount: 0.2,
      type: 'headset',
      tag: 'sale',
    },
    {
      product_name: 'Razer BlackShark V2 Pro Wireless Gaming Headset',
      description: 'Razer BlackShark V2 Pro Wireless Gaming Headset: THX 7.1 Spatial Surround Sound - 50mm Drivers - Detachable Mic - for PC, PS4, PS5, Switch, Xbox One, Xbox Series X & S - 3.5mm Headphone Jack - Black',
      price: 179.99,
      stock: 15,
      category_id: 2,
      manufacturer_id: 4,
      discount: 0.3,
      type: 'headset',
      tag: 'sale',
    },
    {
      product_name: 'Logitech G733 Lightspeed Wireless Gaming Headset',
      description: 'Logitech G733 Lightspeed Wireless Gaming Headset with Suspension Headband, LIGHTSYNC RGB, Blue VO!CE mic Technology and PRO-G Audio Drivers - Black',
      price: 129.99,
      stock: 20,
      category_id: 2,
      manufacturer_id: 2,
      discount: 0.2,
      type: 'headset',
      tag: 'sale',
    },
    {
      product_name: 'Razer Kraken Gaming Headset',
      description: 'Razer Kraken Gaming Headset: Lightweight Aluminum Frame - Retractable Noise Isolating Microphone - for PC, PS4, PS5, Switch, Xbox One, Xbox Series X & S, Mobile - 3.5 mm Headphone Jack - Black/Blue',
      price: 79.99,
      stock: 30,
      category_id: 2,
      manufacturer_id: 4,
      discount: 0,
      type: 'headset',
      tag: 'featured',
    },
    {
      product_name: 'SteelSeries Arctis 1 Wired Gaming Headset',
      description: 'SteelSeries Arctis 1 Wired Gaming Headset – Detachable ClearCast Microphone – Lightweight Steel-Reinforced Headband – for PC, PS5, PS4, Xbox, Nintendo Switch, Mobile',
      price: 49.99,
      stock: 25,
      category_id: 2,
      manufacturer_id: 3,
      discount: 0,
      type: 'headset',
      tag: 'new',
    },
    {
      product_name: 'HyperX Cloud II - Gaming Headset',
      description: 'HyperX Cloud II - Gaming Headset, 7.1 Surround Sound, Memory Foam Ear Pads, Durable Aluminum Frame, Detachable Microphone, Works with PC, PS4, PS4 PRO, Xbox One, Xbox One S - Red',
      price: 79.99,
      stock: 20,
      category_id: 2,
      manufacturer_id: 1,
      discount: 0.2,
      type: 'headset',
      tag: 'sale',
    },
    {
      product_name: 'Razer Kraken Tournament Edition Gaming Headset',
      description: 'Razer Kraken Tournament Edition THX 7.1 Surround Sound Gaming Headset: Aluminum Frame - Retractable Noise Cancelling Mic - USB DAC Included - For PC, PS4, Nintendo Switch - Classic Black',
      price: 79.99,
      stock: 15,
      category_id: 3,
      manufacturer_id: 4,
      discount: 0.2,
      type: 'headset',
      tag: 'sale',
    },
    {
      product_name: 'SteelSeries Arctis 3 - All-Platform Gaming Headset',
      description: 'SteelSeries Arctis 3 - All-Platform Gaming Headset - for PC, PlayStation 4, Xbox One, Nintendo Switch, VR, Android, and iOS - Black',
      price: 69.99,
      stock: 10,
      category_id: 3,
      manufacturer_id: 3,
      discount: 0,
      type: 'headset',
      tag: 'featured',
    },
    {
      product_name: 'HP 14 Ultral Light Laptop for Students and Business',
      description: 'HP 14 Ultral Light Laptop for Students and Business, Intel Quad-Core, 8GB RAM, 192GB Storage(64GB eMMC+128GB Ghost Manta SD Card), 1 Year Office 365, USB C, Win 11 S',
      price: 349.99,
      stock: 30,
      category_id: 1,
      manufacturer_id: 5,
      discount: 0,
      type: 'laptop',
      tag: 'new',
    },
    {
      product_name: 'HP 15 Laptop',
      description: 'HP 15 Laptop, 11th Gen Intel Core i5-1135G7 Processor, 8 GB RAM, 256 GB SSD Storage, 15.6” Full HD IPS Display, Windows 11 Home, HP Fast Charge, Lightweight Design (15-dy2021nr, 2020)',
      price: 599.99,
      stock: 20,
      category_id: 1,
      manufacturer_id: 5,
      discount: 0.2,
      type: 'laptop',
      tag: 'sale',
    },
    {
      product_name: 'Acer Aspire 5 Slim Laptop',
      description: 'Acer Aspire 5 Slim Laptop, 15.6 inches Full HD IPS Display, AMD Ryzen 3 3200U, Vega 3 Graphics, 4GB DDR4, 128GB SSD, Backlit Keyboard, Windows 10 in S Mode, A515-43-R19L, Silver',
      price: 364.99,
      stock: 15,
      category_id: 1,
      manufacturer_id: 6,
      discount: 0,
      type: 'laptop',
      tag: 'new',
    },
    {
      product_name: 'ASUS VivoBook 15 Thin and Light Laptop',
      description: 'ASUS VivoBook 15 Thin and Light Laptop, 15.6” FHD Display, Intel i3-1005G1 CPU, 8GB RAM, 128GB SSD, Backlit Keyboard, Fingerprint, Windows 10 Home in S Mode, Slate Gray, F512JA-AS34',
      price: 399.99,
      stock: 10,
      category_id: 1,
      manufacturer_id: 1,
      discount: 0,
      type: 'laptop',
      tag: 'new',
    },
    {
      product_name: 'Lenovo IdeaPad 3 Laptop',  
      description: 'Lenovo IdeaPad 3 Laptop, 15.6 HD Display, AMD Ryzen 3 3250U, 4GB RAM, 128GB Storage, Windows 10 Home in S Mode, 81W1009DUS, Abyss Blue',
      price: 299.99,
      stock: 10,
      category_id: 1,
      manufacturer_id: 2,
      discount: 0,
      type: 'laptop',
      tag: 'new',
    },
    {
      product_name: 'Acer Chromebook Spin 311 Convertible Laptop',
      description: 'Acer Chromebook Spin 311 Convertible Laptop, Intel Celeron N4020, 11.6 HD Touch, 4GB LPDDR4, 32GB eMMC, Gigabit Wi-Fi 5, Bluetooth 5.0, Google Chrome, CP311-2H-C679',
      price: 269.99,
      stock: 10,
      category_id: 1,
      manufacturer_id: 6,
      discount: 0,
      type: 'laptop',
      tag: 'new',
    },
    {
      product_name: 'HP Pavilion x360 Convertible Laptop',
      description: 'HP Pavilion x360 Convertible Laptop, Intel Core i3, 14\' FHD Touch, 8GB RAM, 256GB SSD, Wi-Fi 6, Bluetooth 5.1, Windows 11 Home',
      price: 499.99,
      stock: 15,
      category_id: 1,
      manufacturer_id: 1,
      discount: 0.1,
      type: 'laptop',
      tag: 'featured'
    },
    {
      product_name: 'Dell Inspiron 15 3000 Series',
      description: 'Dell Inspiron 15 3000 Series, Intel Core i5, 15.6\' FHD, 12GB RAM, 512GB SSD, Windows 11 Home',
      price: 599.99,
      stock: 8,
      category_id: 2,
      manufacturer_id: 2,
      discount: 0.05,
      type: 'laptop',
      tag: 'sale'
    },
    {
      product_name: 'Lenovo IdeaPad Flex 5',
      description: 'Lenovo IdeaPad Flex 5, AMD Ryzen 5, 14\' FHD Touch, 8GB RAM, 256GB SSD, Wi-Fi 6, Bluetooth 5.0, Windows 11',
      price: 479.99,
      stock: 12,
      category_id: 3,
      manufacturer_id: 3,
      discount: 0.1,
      type: 'laptop',
      tag: 'new'
    },
    {
      product_name: 'ASUS VivoBook Flip 14',
      description: 'ASUS VivoBook Flip 14, Intel Core i7, 14\' FHD Touch, 16GB RAM, 1TB SSD, Windows 11 Pro',
      price: 849.99,
      stock: 5,
      category_id: 4,
      manufacturer_id: 4,
      discount: 0.15,
      type: 'laptop',
      tag: 'featured'
    },
    {
      product_name: 'Samsung Galaxy Chromebook 2',
      description: 'Samsung Galaxy Chromebook 2, Intel Celeron, 13.3\' QLED Touch, 8GB RAM, 128GB eMMC, Chrome OS',
      price: 419.99,
      stock: 20,
      category_id: 5,
      manufacturer_id: 5,
      discount: 0.2,
      type: 'laptop',
      tag: 'sale'
    },
    {
      product_name: 'Microsoft Surface Laptop Go',
      description: 'Microsoft Surface Laptop Go, Intel Core i5, 12.4\' Touchscreen, 8GB RAM, 128GB SSD, Windows 11 Home',
      price: 629.99,
      stock: 7,
      category_id: 6,
      manufacturer_id: 6,
      discount: 0,
      type: 'laptop',
      tag: 'new'
    },
    {
      product_name: 'Acer Swift 3 Thin & Light Laptop',
      description: 'Acer Swift 3 Thin & Light Laptop, AMD Ryzen 7, 14\' FHD, 8GB RAM, 512GB SSD, Wi-Fi 6, Windows 11',
      price: 669.99,
      stock: 10,
      category_id: 7,
      manufacturer_id: 1,
      discount: 0.05,
      type: 'laptop',
      tag: 'featured'
    },
    {
      product_name: 'HP Chromebook 14',
      description: 'HP Chromebook 14, Intel Celeron, 14\' HD, 4GB RAM, 64GB eMMC, Chrome OS',
      price: 269.99,
      stock: 18,
      category_id: 8,
      manufacturer_id: 2,
      discount: 0.1,
      type: 'laptop',
      tag: 'sale'
    },
    {
      product_name: 'Dell XPS 13 2-in-1',
      description: 'Dell XPS 13 2-in-1, Intel Core i7, 13.4\' FHD Touch, 16GB RAM, 512GB SSD, Windows 11 Pro',
      price: 1099.99,
      stock: 6,
      category_id: 9,
      manufacturer_id: 3,
      discount: 0.2,
      type: 'laptop',
      tag: 'new'
    },
    {
      product_name: 'Lenovo ThinkPad X1 Carbon Gen 9',
      description: 'Lenovo ThinkPad X1 Carbon Gen 9, Intel Core i7, 14\' UHD, 16GB RAM, 1TB SSD, Windows 11 Pro',
      price: 1429.99,
      stock: 4,
      category_id: 10,
      manufacturer_id: 4,
      discount: 0.1,
      type: 'laptop',
      tag: 'featured'
    },
    {
      product_name: 'ASUS ZenBook 13 OLED',
      description: 'ASUS ZenBook 13 OLED, AMD Ryzen 7, 13.3\' OLED, 16GB RAM, 512GB SSD, Windows 11 Home',
      price: 899.99,
      stock: 11,
      category_id: 1,
      manufacturer_id: 5,
      discount: 0.05,
      type: 'laptop',
      tag: 'sale'
    },
    {
      product_name: 'Samsung Notebook Plus 2',
      description: 'Samsung Notebook Plus 2, Intel Core i5, 15.6\' FHD, 8GB RAM, 256GB SSD, Windows 11 Home',
      price: 749.99,
      stock: 9,
      category_id: 2,
      manufacturer_id: 6,
      discount: 0.15,
      type: 'laptop',
      tag: 'new'
    },
    {
      product_name: 'Acer Aspire 5 Slim Laptop',
      description: 'Acer Aspire 5 Slim Laptop, AMD Ryzen 5, 15.6\' FHD, 8GB RAM, 256GB SSD, Wi-Fi 6, Windows 11 Home',
      price: 449.99,
      stock: 14,
      category_id: 3,
      manufacturer_id: 1,
      discount: 0.1,
      type: 'laptop',
      tag: 'featured'
    },
    {
      product_name: 'HP Envy x360 Convertible Laptop',
      description: 'HP Envy x360 Convertible Laptop, AMD Ryzen 7, 15.6\' FHD Touch, 16GB RAM, 512GB SSD, Windows 11 Home',
      price: 979.99,
      stock: 5,
      category_id: 4,
      manufacturer_id: 2,
      discount: 0.05,
      type: 'laptop',
      tag: 'sale'
    },
    {
      product_name: 'Dell Latitude 7420',
      description: 'Dell Latitude 7420, Intel Core i7, 14\' FHD, 16GB RAM, 512GB SSD, Windows 11 Pro',
      price: 1299.99,
      stock: 3,
      category_id: 5,
      manufacturer_id: 3,
      discount: 0.1,
      type: 'laptop',
      tag: 'new'
    },
    {
      product_name: 'Lenovo Yoga 7i',
      description: 'Lenovo Yoga 7i, Intel Core i5, 14\' FHD Touch, 8GB RAM, 256GB SSD, Windows 11 Home',
      price: 799.99,
      stock: 10,
      category_id: 6,
      manufacturer_id: 4,
      discount: 0,
      type: 'laptop',
      tag: 'featured'
    },
    {
      product_name: 'ASUS ROG Zephyrus G14',
      description: 'ASUS ROG Zephyrus G14, AMD Ryzen 9, 14\' QHD, 16GB RAM, 1TB SSD, Windows 11 Home',
      price: 1599.99,
      stock: 7,
      category_id: 7,
      manufacturer_id: 5,
      discount: 0.2,
      type: 'laptop',
      tag: 'sale'
    },
    {
      product_name: 'Samsung Galaxy Book Pro',
      description: 'Samsung Galaxy Book Pro, Intel Core i5, 13.3\' AMOLED, 8GB RAM, 256GB SSD, Windows 11 Home',
      price: 1149.99,
      stock: 6,
      category_id: 8,
      manufacturer_id: 6,
      discount: 0.1,
      type: 'laptop',
      tag: 'new'
    },
    {
      product_name: 'Microsoft Surface Pro 7+',
      description: 'Microsoft Surface Pro 7+, Intel Core i5, 12.3\' Touch, 8GB RAM, 256GB SSD, Windows 11 Pro',
      price: 899.99,
      stock: 5,
      category_id: 9,
      manufacturer_id: 1,
      discount: 0.15,
      type: 'laptop',
      tag: 'featured'
    },
    {
      product_name: 'Samsung Galaxy A15 A155M 128GB',
      description: 'Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Blue Black',
      price: 148.7,
      stock: 10,
      category_id: 10,
      manufacturer_id: 6,
      discount: 0,
      type: 'phone',
      tag: 'new'
    },
    {
      product_name: 'Samsung Galaxy A05 A055M 64GB',
      description: 'Samsung Galaxy A05 A055M 64GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Black',
      price: 89.67,
      stock: 15,
      category_id: 1,
      manufacturer_id: 1,
      discount: 0.1,
      type: 'phone',
      tag: 'sale'
    },
    {
      product_name: 'Samsung Galaxy A15 A155M 128GB',
      description: 'Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Blue Black',
      price: 148.7,
      stock: 10,
      category_id: 2,
      manufacturer_id: 6,
      discount: 0,
      type: 'phone',
      tag: 'featured'
    },
    {
      product_name: 'Samsung Galaxy A05 A055M 64GB',
      description: 'Samsung Galaxy A05 A055M 64GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Black',
      price: 89.67,
      stock: 15,
      category_id: 3,
      manufacturer_id: 1,
      discount: 0.1,
      type: 'phone',
      tag: 'sale'
    },
    {
      product_name: 'Samsung Galaxy A15 A155M 128GB',
      description: 'Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Blue Black',
      price: 148.7,
      stock: 10,
      category_id: 4,
      manufacturer_id: 6,
      discount: 0,
      type: 'phone',
      tag: 'new'
    },
    {
      product_name: 'Moto G Play',
      description: 'Moto G Play | 2024 | Unlocked | Made for US 4/64GB | 50MP Camera | Sapphire Blue',
      price: 169.99,
      stock: 5,
      category_id: 5,
      manufacturer_id: 1,
      discount: 0.15,
      type: 'phone',
      tag: 'featured'
    },
    {
      product_name: 'AT&T BL102-3 DECT 6.0 3-Handset Cordless Phone',
      description: 'AT&T BL102-3 DECT 6.0 3-Handset Cordless Phone for Home with Answering Machine, Call Blocking, Caller ID Announcer, Audio Assist, Intercom, and Unsurpassed Range, Silver/Black',
      price: 69.95,
      stock: 10,
      category_id: 6,
      manufacturer_id: 2,
      discount: 0.1,
      type: 'phone',
      tag: 'sale'
    },
    {
      product_name: 'VTech CS6114 DECT 6.0 Cordless Phone',
      description: 'VTech CS6114 DECT 6.0 Cordless Phone for Home with Answering Machine, Call Blocking, Caller ID Announcer, Audio Assist, Intercom, and Unsurpassed Range, Silver/Black',
      price: 79.95,
      stock: 5,
      category_id: 7,
      manufacturer_id: 2,
      discount: 0.15,
      type: 'phone',
      tag: 'featured'
    },
    {
      product_name: 'Apple iPhone 12, 64GB, Black - Fully',
      description: 'Apple iPhone 12, 64GB, Black - Fully Unlocked (Renewed)',
      price: 599.99,
      stock: 10,
      category_id: 8,
      manufacturer_id: 3,
      discount: 0,
      type: 'phone',
      tag: 'new'
    },
    {
      product_name: 'Samsung Galaxy S21, 128GB, Phantom Gray',
      description: 'Samsung Galaxy S21, 128GB, Phantom Gray - Unlocked (Renewed)',
      price: 499.99,
      stock: 15,
      category_id: 3,
      manufacturer_id: 1,
      discount: 0.1,
      type: 'phone',
      tag: 'sale'
    },
    {
      product_name: 'Google Pixel 6, 128GB, Stormy Black',
      description: 'Google Pixel 6, 128GB, Stormy Black - Factory Unlocked',
      price: 599.00,
      stock: 8,
      category_id: 2,
      manufacturer_id: 2,
      discount: 0,
      type: 'phone',
      tag: 'new'
    },
    {
      product_name: 'Xiaomi Mi 11, 256GB, Horizon Blue',
      description: 'Xiaomi Mi 11, 256GB, Horizon Blue - Global Version',
      price: 699.99,
      stock: 12,
      category_id: 4,
      manufacturer_id: 5,
      discount: 0.05,
      type: 'phone',
      tag: 'featured'
    },
    {
      product_name: 'OnePlus 9, 128GB, Astral Black',
      description: 'OnePlus 9, 128GB, Astral Black - 5G Factory Unlocked',
      price: 549.99,
      stock: 20,
      category_id: 5,
      manufacturer_id: 4,
      discount: 0,
      type: 'phone',
      tag: 'new'
    },
    {
      product_name: 'Apple iPhone 13, 128GB, Midnight',
      description: 'Apple iPhone 13, 128GB, Midnight - Unlocked',
      price: 799.00,
      stock: 10,
      category_id: 6,
      manufacturer_id: 3,
      discount: 0,
      type: 'phone',
      tag: 'featured'
    },
    {
      product_name: 'Huawei P40 Pro, 256GB, Silver Frost',
      description: 'Huawei P40 Pro, 256GB, Silver Frost - International Version',
      price: 649.99,
      stock: 6,
      category_id: 7,
      manufacturer_id: 6,
      discount: 0.15,
      type: 'phone',
      tag: 'sale'
    },
    {
      product_name: 'Realme GT, 128GB, Racing Yellow',
      description: 'Realme GT, 128GB, Racing Yellow - Flagship Performance',
      price: 499.99,
      stock: 25,
      category_id: 1,
      manufacturer_id: 5,
      discount: 0,
      type: 'phone',
      tag: 'new'
    },
    {
      product_name: 'Sony Xperia 1 III, 256GB, Frosted Black',
      description: 'Sony Xperia 1 III, 256GB, Frosted Black - 4K OLED Display',
      price: 999.99,
      stock: 5,
      category_id: 8,
      manufacturer_id: 6,
      discount: 0.2,
      type: 'phone',
      tag: 'featured'
    },
    {
      product_name: 'Motorola Edge 20, 128GB, Frosted White',
      description: 'Motorola Edge 20, 128GB, Frosted White - Slim and Powerful',
      price: 399.99,
      stock: 18,
      category_id: 9,
      manufacturer_id: 2,
      discount: 0.1,
      type: 'phone',
      tag: 'sale'
    },
    {
      product_name: 'Vivo X70 Pro, 256GB, Cosmic Black',
      description: 'Vivo X70 Pro, 256GB, Cosmic Black - ZEISS Optics',
      price: 729.99,
      stock: 8,
      category_id: 10,
      manufacturer_id: 5,
      discount: 0.05,
      type: 'phone',
      tag: 'new'
    },
    {
      product_name: 'Oppo Find X3, 256GB, Gloss Black',
      description: 'Oppo Find X3, 256GB, Gloss Black - Dual 50MP Cameras',
      price: 849.99,
      stock: 7,
      category_id: 2,
      manufacturer_id: 4,
      discount: 0.15,
      type: 'phone',
      tag: 'featured'
    },
    {
      product_name: 'Asus ROG Phone 5, 128GB, Phantom Black',
      description: 'Asus ROG Phone 5, 128GB, Phantom Black - Gaming Beast',
      price: 999.99,
      stock: 3,
      category_id: 4,
      manufacturer_id: 6,
      discount: 0.25,
      type: 'phone',
      tag: 'sale'
    },
    {
      product_name: 'Nokia G20, 64GB, Glacier',
      description: 'Nokia G20, 64GB, Glacier - Long Battery Life',
      price: 199.99,
      stock: 30,
      category_id: 3,
      manufacturer_id: 1,
      discount: 0,
      type: 'phone',
      tag: 'new'
    },
    {
      product_name: 'Samsung Galaxy Z Fold 3, 256GB, Phantom Green',
      description: 'Samsung Galaxy Z Fold 3, 256GB, Phantom Green - Foldable Innovation',
      price: 1799.99,
      stock: 2,
      category_id: 5,
      manufacturer_id: 1,
      discount: 0.3,
      type: 'phone',
      tag: 'featured'
    },
    {
      product_name: 'Google Pixel 5a, 128GB, Mostly Black',
      description: 'Google Pixel 5a, 128GB, Mostly Black - Affordable Excellence',
      price: 449.99,
      stock: 22,
      category_id: 6,
      manufacturer_id: 2,
      discount: 0,
      type: 'phone',
      tag: 'new'
    },
    {
      product_name: 'Xiaomi Redmi Note 10, 128GB, Shadow Black',
      description: 'Xiaomi Redmi Note 10, 128GB, Shadow Black - Budget Champion',
      price: 299.99,
      stock: 40,
      category_id: 7,
      manufacturer_id: 5,
      discount: 0.1,
      type: 'phone',
      tag: 'sale'
    },
    {
      product_name: 'Apple MacBook Air M2, 256GB, Silver',
      description: 'Apple MacBook Air M2, 256GB, Silver - Lightweight Powerhouse',
      price: 999.99,
      stock: 15,
      category_id: 10,
      manufacturer_id: 1,
      discount: 0.05,
      type: 'laptop',
      tag: 'new'
    },
    {
      product_name: 'Dell XPS 13, 512GB, Platinum Silver',
      description: 'Dell XPS 13, 512GB, Platinum Silver - Premium Ultrabook',
      price: 1299.99,
      stock: 10,
      category_id: 11,
      manufacturer_id: 3,
      discount: 0.1,
      type: 'laptop',
      tag: 'sale'
    },
    {
      product_name: 'HP Omen 16, 1TB SSD, Shadow Black',
      description: 'HP Omen 16, 1TB SSD, Shadow Black - Gaming Beast',
      price: 1499.99,
      stock: 8,
      category_id: 12,
      manufacturer_id: 2,
      discount: 0.15,
      type: 'laptop',
      tag: 'featured'
    },
    {
      product_name: 'Lenovo Legion 5, 512GB SSD, Phantom Blue',
      description: 'Lenovo Legion 5, 512GB SSD, Phantom Blue - Performance Champion',
      price: 1149.99,
      stock: 12,
      category_id: 13,
      manufacturer_id: 4,
      discount: 0,
      type: 'laptop',
      tag: 'new'
    },
    {
      product_name: 'Razer Blade 15, 1TB SSD, Black',
      description: 'Razer Blade 15, 1TB SSD, Black - Sleek Gaming Power',
      price: 1999.99,
      stock: 5,
      category_id: 14,
      manufacturer_id: 6,
      discount: 0.2,
      type: 'laptop',
      tag: 'sale'
    },
    {
      product_name: 'Samsung Galaxy Buds Pro, Phantom Black',
      description: 'Samsung Galaxy Buds Pro, Phantom Black - Immersive Sound',
      price: 199.99,
      stock: 50,
      category_id: 15,
      manufacturer_id: 5,
      discount: 0.1,
      type: 'headset',
      tag: 'featured'
    },
    {
      product_name: 'Sony WH-1000XM5, Silver',
      description: 'Sony WH-1000XM5, Silver - Noise Cancelling Excellence',
      price: 349.99,
      stock: 20,
      category_id: 16,
      manufacturer_id: 1,
      discount: 0.05,
      type: 'headset',
      tag: 'new'
    },
    {
      product_name: 'Logitech G Pro X, Black',
      description: 'Logitech G Pro X, Black - Pro Gaming Headset',
      price: 129.99,
      stock: 25,
      category_id: 17,
      manufacturer_id: 3,
      discount: 0,
      type: 'headset',
      tag: 'new'
    },
    {
      product_name: 'Corsair K95 RGB Platinum XT, Black',
      description: 'Corsair K95 RGB Platinum XT, Black - Premium Gaming Keyboard',
      price: 199.99,
      stock: 18,
      category_id: 10,
      manufacturer_id: 2,
      discount: 0.1,
      type: 'keyboard',
      tag: 'sale'
    },
    {
      product_name: 'Razer Huntsman Elite, Black',
      description: 'Razer Huntsman Elite, Black - Ultimate Gaming Keyboard',
      price: 249.99,
      stock: 22,
      category_id: 11,
      manufacturer_id: 6,
      discount: 0.15,
      type: 'keyboard',
      tag: 'featured'
    },
    {
      product_name: 'SteelSeries Apex Pro, Black',
      description: 'SteelSeries Apex Pro, Black - Adjustable Gaming Keyboard',
      price: 179.99,
      stock: 30,
      category_id: 12,
      manufacturer_id: 5,
      discount: 0.1,
      type: 'keyboard',
      tag: 'new'
    },
    {
      product_name: 'HyperX Alloy FPS Pro, Red',
      description: 'HyperX Alloy FPS Pro, Red - Compact Gaming Keyboard',
      price: 99.99,
      stock: 40,
      category_id: 13,
      manufacturer_id: 4,
      discount: 0.05,
      type: 'keyboard',
      tag: 'sale'
    },
    {
      product_name: 'Microsoft Surface Laptop 5, 256GB, Platinum',
      description: 'Microsoft Surface Laptop 5, 256GB, Platinum - Elegant and Powerful',
      price: 1299.99,
      stock: 14,
      category_id: 14,
      manufacturer_id: 1,
      discount: 0.05,
      type: 'laptop',
      tag: 'featured'
    },
    {
      product_name: 'Asus ROG Strix Scar 17, 1TB SSD, Black',
      description: 'Asus ROG Strix Scar 17, 1TB SSD, Black - Gaming Masterpiece',
      price: 2499.99,
      stock: 6,
      category_id: 15,
      manufacturer_id: 6,
      discount: 0.1,
      type: 'laptop',
      tag: 'sale'
    },
    {
      product_name: 'Apple AirPods Max, Space Gray',
      description: 'Apple AirPods Max, Space Gray - Premium Over-Ear Audio',
      price: 549.99,
      stock: 15,
      category_id: 16,
      manufacturer_id: 1,
      discount: 0.05,
      type: 'headset',
      tag: 'new'
    },
    {
      product_name: 'Bose QuietComfort 45, Black',
      description: 'Bose QuietComfort 45, Black - Iconic Noise Cancelling',
      price: 329.99,
      stock: 20,
      category_id: 17,
      manufacturer_id: 2,
      discount: 0,
      type: 'headset',
      tag: 'featured'
    },
    {
      product_name: 'Xiaomi Mi Notebook Pro 14, 512GB SSD, Silver',
      description: 'Xiaomi Mi Notebook Pro 14, 512GB SSD, Silver - Affordable Workhorse',
      price: 899.99,
      stock: 25,
      category_id: 10,
      manufacturer_id: 5,
      discount: 0.05,
      type: 'laptop',
      tag: 'new'
    },
    {
      product_name: 'Samsung Galaxy Book 3 Pro, 1TB SSD, Mystic Silver',
      description: 'Samsung Galaxy Book 3 Pro, 1TB SSD, Mystic Silver - Sleek Productivity',
      price: 1499.99,
      stock: 10,
      category_id: 11,
      manufacturer_id: 4,
      discount: 0.1,
      type: 'laptop',
      tag: 'sale'
    },
    {
      product_name: 'Dell Inspiron 15, 512GB SSD, Black',
      description: 'Dell Inspiron 15, 512GB SSD, Black - Everyday Performance',
      price: 749.99,
      stock: 20,
      category_id: 12,
      manufacturer_id: 3,
      discount: 0,
      type: 'laptop',
      tag: 'featured'
    },
    {
      product_name: 'Razer Kraken X, Black',
      description: 'Razer Kraken X, Black - Lightweight Gaming Headset',
      price: 49.99,
      stock: 50,
      category_id: 13,
      manufacturer_id: 6,
      discount: 0.2,
      type: 'headset',
      tag: 'sale'
    }
    
  ]);
};
